apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
# Kubeflow namespace
- ../../../common/kubeflow-namespace/base
# Kubeflow Roles
- ../../../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../../../common/istio-1-16/kubeflow-istio-resources/base
# Kubeflow Pipelines
- ../../../apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
# Katib
- ../../../apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
# Michał: to be replaced by custom overlay
# - ../../../apps/centraldashboard/upstream/overlays/kserve
# Admission Webhook
- ../../../apps/admission-webhook/upstream/overlays/cert-manager
# Jupyter Web App
- ../../../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Notebook Controller
- ../../../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../../../apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../../../apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
-  ../../../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
-  ../../../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- ../../../apps/training-operator/upstream/overlays/kubeflow
# User namespace
# Michal: to be replaced by custom profiles
# - ../../../common/user-namespace/base
# KServe
- ../../../contrib/kserve/kserve
- ../../../contrib/kserve/models-web-app/overlays/kubeflow
