apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
- ../../../common/cert-manager/cert-manager/base
- ../../../common/cert-manager/kubeflow-issuer/base
# Istio
- ../../../common/istio-1-16/istio-crds/base

# - ../../../common/istio-1-16/istio-namespace/base
- ../../../common/istio-1-16/istio-install/base
# OIDC Authservice
# Michał: to be replaced by custom overlay
# - ../../../common/oidc-authservice/base
# Dex
# Michał: to be replaced by custom overlay
# - ../../../common/dex/overlays/istio
# KNative
- ../../../common/knative/knative-serving/overlays/gateways
- ../../../common/knative/knative-eventing/base
- ../../../common/istio-1-16/cluster-local-gateway/base