apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      k8s:
        service:
          ports:
          - name: http2
            port: 80
            targetPort: 8080
            nodePort: 31916
