name: Build, kustomize and deploy

on:
  - push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ENVIRONMENT: [staging, development]
        ROOT_DIR: [kubeflow_core, kubeflow_core_namespaces, kubeflow_components, kubeflow_components_namespaces]

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install kustomize
      run: ./tests/gh-actions/install_kustomize.sh

    - name: Run kustomize on ${{ matrix.ROOT_DIR }} on ${{ matrix.ENVIRONMENT }}
      run: |
        kustomize build deployment/${{ matrix.ROOT_DIR }}/${{ matrix.ENVIRONMENT }} | tee install_${{ matrix.ROOT_DIR }}_${{ matrix.ENVIRONMENT }}.yaml
        if [ ! -s install_${{ matrix.ROOT_DIR }}_${{ matrix.ENVIRONMENT }}.yaml ]; then
          echo "install_${{ matrix.ROOT_DIR }}_${{ matrix.ENVIRONMENT }}.yaml is empty"
          exit 1
        fi
    
    - name: Upload install_${{ matrix.ROOT_DIR }}_${{ matrix.ENVIRONMENT }}.yaml on ${{ matrix.ROOT_DIR }} on ${{ matrix.ENVIRONMENT }}
      uses: actions/upload-artifact@v3
      with:
        name: install_${{ matrix.ROOT_DIR }}_${{ matrix.ENVIRONMENT }}.yaml
        path: install_${{ matrix.ROOT_DIR }}_${{ matrix.ENVIRONMENT }}.yaml
        retention-days: 5
